theme:
  - osuny-alumni-theme
  - osuny-campus-art-mediterrannee-footer
  - osuny
_merge: deep
params:
  summary:
    position: hero
  search:
    active: true
  logo:
    header: ''
    footer: ''
  home:
    head:
      title: site
  breadcrumb:
    position: none
  persons:
    index:
      layout: grid
      options:
        cohorts: true
  alumni:
    menu:
      programs:
        exclude_children: true

pagination:
  pagerSize: 2